### PR TITLE
Fix in Japanese translation

### PR DESCRIPTION
**Pull request by orangain**
- Fix typo.
- Show an English title beside Japanese one as shared vocabulary between languages.

### CODE REVIEW

**Comment by mahnunchik** [comment]
Hi,
I think titles in English should be present in every translation.

**Comment by jonmountjoy** [comment]
What's the reasoning behind showing English titles in every translation?  I mean, it would help me, and English speaker, but how does it help the translated-language reader?

**Comment by jonmountjoy** [comment]
(BTW I integrated the other commit, https://github.com/orangain/12factor/commit/503009acdcf6474165a71fd284d0026261c28377 )

**Comment by orangain** [comment]
English titles help the translated-language reader discuss with English or other language speakers about their application's architecture. They can understand the twelve factors by their native language, and then discuss with others using English titles as a shared vocabulary.

For this purpose, I agree with mahnunchik. But I don't know the general brackets used in languages other than Japanese. It's wonderful if the other languages' translator add titles in English.

Furthermore, there can be more than one translations in some languages. e.g. I've translated "Backing services" to "バックエンドサービス", but the other person to "バッキングサービス". Though both of them are ok, English titles can become a shared vocabulary even among Japanese people.

**Comment by jonmountjoy** [comment]
Thanks @orangain . I think if we do that we should do it programmatically - perhaps at the table of content level and top level heading page only?

**Comment by orangain** [comment]
@jonmountjoy do you mean it's not DRY to modify titles at both contents' *.md and toc.md? In that case, how about removing toc.md and generating TOC from contents' *.md files?

**Comment by raul** [comment]
Moving the discussion to https://github.com/heroku/12factor/issues/168

**Pull request closed without merging**
