### PR TITLE
fix insecure links and update http to https

### PR DESCRIPTION
**Pull request by lpmi-13**
Using `target="_blank"` is a security risk for link-jacking. To secure this a bit, we can add `noopener` or `noreferrer`. Generally, both are added to accommodate older browsers that don't support `noopener`.

This commit also updates a lot of the http links to https, where possible.

### CODE REVIEW

**Comment by danidr7** [comment]
Heey @lpmi-13, nice job here!
However, i think is better do not use the `noreferrer`, as it hides the reference of visitors.
It may be interesting to see that the origin of visitors is factor 12.

Some references about it:
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer
https://www.reliablesoft.net/noreferrer-noopener/

**Comment by lpmi-13** [comment]
Sure. I'll update this PR to reflect that.

**Comment by lpmi-13** [comment]
pushed a commit with that update. Happy to rebase after approval or whatever you usually do.

**Review by danidr7 — APPROVED** [review]
LGTM!

**Pull request closed without merging**
