### PR TITLE
Change HTML lang attribute to equal current locale

### PR DESCRIPTION
**Pull request by olapokon**
I was looking at the website and noticed that the HTML lang is hard-coded to "en". Submitting a pull request with a minor adjustment.

### CODE REVIEW

**Comment by davidrouten** [comment]
@raul @hannesfostie, this looks good to me, is there anything else we should take into consideration when setting the `html lang` attribute to equal whatever current translation we are serving up?

**Comment by raul** [comment]
Great catch! 

Looks like [the W3C recommends](https://www.w3.org/International/questions/qa-html-language-declarations) using [this set of language subtags](http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry). 

Comparing those tags with the ones in [the content](https://github.com/heroku/12factor/tree/master/content) and [locales](https://github.com/heroku/12factor/tree/master/locales) directories looks like `pt_br` should generate `lang="pt-BR"` and `zh_cn` should be... I can't tell, perhaps use just `lang="zh"` for now?

(I'm guessing `I18n.locale` doesn't cake care of the underscore -> dash conversion?).

**Comment by ak4ra** [comment]
Hi,

I just checked, and I18n.locale does not show the dash in place of an underscore, so the lang appears as pt_br and zh_cn in these two cases.

**Comment by ak4ra** [comment]
Maybe something like this at web.rb line 68? To call in place of `I18n.locale` in layout.erb

`  def format_lang()
    case String(I18n.locale)
    when "zh_cn"
      "zh"
    when "pt_br"
      "pt-br"
    else
      I18n.locale
    end
  end`

I've never actually written anything in Ruby before.

**Pull request closed without merging**
