### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by Jaza**
Complete translation of the 12factor.net content into Spanish.

Note: I'm not a native speaker (I've lived for about 3 years total in South America, mainly Chile), and this is my first big EN-ES translation. So, review / corrections would be welcome and appreciated.

However, I believe that my translation is complete and grokkable enough to be merged (in the interests of "commit early, commit often"), and for improvements to be made by others in separate PRs.

### CODE REVIEW

**Comment by raul** [comment]
Hey @Jaza, thank you for the translation, it's very impressive coming from a non-native speaker! :) I'd like to do a first quick review before shipping it, time-boxed to this week to follow the "release early, release often" principle you mention. Thanks again!

**Comment by Jaza** [comment]
@raul - Ahhh, sorry, didn't see #42 - I looked before starting, to see if anyone else had begun work on a Spanish translation, but I missed that thread. Anyway, looks like not much progress had been made on it, so I guess closing it is the right thing to do. And yes, review of my translation would be great.

**Comment by raul** [comment]
Update: I spent a few days offline so I've only reviewed about half of the docs so far but I'll keep making progress, should have something shippable by the end of the week.

**Comment by sblancov** [comment]
Hi guys, I am from Madrid, Spain and I am a little disapointed because there is no Spanish translation of this useful material in your web. So, I have started to do it (this is my third day working on it). Unfortunatelly, I did not see this one until now. Anyway, I am going to finish my translation because I want to practice my skills, so you will receive another pull request in the near future about this topic.

I do not want to understimate your work and I hope do not offend you @Jaza.

**Comment by Jaza** [comment]
No problem, @sblancov - I also did the translation to practice my skills (and I guess @alvarogarcia7 started his for the same reason), so it's only fair that you do the same. Although, considering that my translation is the only one that's complete right now, it would be great if you could read the text I've done, and incorporate the better parts of it into your text.

At the end of the day, we want the best translation to actually get merged and published, and to then be read and understood by others. So, may the best pull request win. ;-)

**Comment by raul** [comment]
Hey @sblancov, it's great to see more people excited about this translation! :)

I've been reviewing this PR for a few days and just pushed https://github.com/heroku/12factor/pull/55, with only three pages to be reviewed before considering it "good enough" for an initial release. I'm still not convinced about its quality (I find translating technical texts a pretty challenging task), so feel free to join the PR with reviews and suggestions or keep working on your own, which may be a valuable iteration.

**Comment by sblancov** [comment]
Definitely, I will take account of your translation, @Jaza, as I am doing already with Italian, Portuguese, and Frech translations to improve my own.

**Comment by raul** [comment]
See https://github.com/heroku/12factor/pull/55#issuecomment-154511140.

**Pull request closed without merging**
