### PR TITLE
Explain the word deploy

### PR DESCRIPTION
**Pull request by diegobfernandez**
The word deploy is commom between developers in Brasil but not to newcomers and people that don't speak english.
I believe translating it increase accessibility to the content.

### CODE REVIEW

**Comment by fernandes** [comment]
hi @diegobfernandez 
When we were working on pt-BR translation there was some technical terms (like deploy), that are most used in english than in portuguese in most technical articles, forums, ...

In Brazil is much more usual some ask for: "alguém poderia me ajudar com o deploy automático", do que "alguém poderia me ajudar com a implantação automática".

That's why, as you said _this is common between developers_ (the main target of 12 factor books) in Brazil, we opted for leaving it as _deploy_.

This is a fine line between what's more accessible and personal preferences, but as anyone has one opinion, mine is to leave it as _deploy_, but the choose on merging is to @jonmountjoy heheh

Thank you

**Comment by diegobfernandez** [comment]
I agree, myself and my team use deploy and despite we usually say "deployados" it does not seem right.
Maybe just replacing "deployados" for "implantados" and adding some note next to the definition of deploy will help clarify and beautify.

e.g.: Um deploy (ou implantação) é uma instância executando a aplicação.

e.g.: alguns registros ainda não ~~deployados~~ implantados no ambiente

**Comment by diegobfernandez** [comment]
I updated the code as I my last comment to simply explain the word and not to translate it.
Is there anything I must do to get it approved (besides wait for your feedback)?

**Comment by fernandes** [comment]
hi @diegobfernandez I liked your alternative.

I don't approve the PR, just helps @jonmountjoy with pt-BR translation hehe but it seems good to me!

@jonmountjoy we are ready to go! 👍 
@diegobfernandez thank you! 🙇

**Comment by jonmountjoy** [comment]
Thank you

**Pull request merged**
