### PR TITLE
Support translations

### PR DESCRIPTION
**Pull request by orangain**
### Changes
This pull-request support translations. I've added Japanese translation.
A visitor can read the translated articles by selecting a language from the navigation at the bottom of pages.

screenshot1 &nbsp; screenshot2

Paths of pages are followings: 
- `/`: The home page in English.
- `/:factor`: Articles in English, e.g. `/codebase`.
- `/ja/`: The home page in Japanese.
- `/ja/:factor`: Articles in Japanese, e.g. `/ja/codebase`.

### Motivation

Last August, I have translated 12factor into Japanese and published at [http://twelve-factor-ja.herokuapp.com/](http://twelve-factor-ja.herokuapp.com/).
A few thousands of people in Japan have read the translation up to now.

If the official site provide translations, a visitor can easily find articles translated into his/her native language.
Then, more and more people can know 12factor's idea, use as a shared vocabulary and discuss on it.

There seem to be some people who are interested in translations:
- [Any plans on supporting translations · Issue #14 · adamwiggins/12factor](https://github.com/adamwiggins/12factor/issues/14)
- [liangshan/12factor](https://github.com/liangshan/12factor)
- [anjuke/12factor](https://github.com/anjuke/12factor)

It's wonderful if the pull-request is merged and translations in other languages are available.

### CODE REVIEW

**Comment by fernandes** [comment]
@orangain great work, I'm gonna apply your code to my fork, ok?

@joncasdam here its https://github.com/12factor/12factor-br PRs are welcome

**Comment by lfilho** [comment]
Almost a year now. Any plans on merging this, @heroku? Ping @adamwiggins

**Comment by fernandes** [comment]
better late than never ;)

**Comment by jonmountjoy** [comment]
Sorry for the delay.  This is merged.  The [Japanese version](http://12factor.net/ja/) is now live.

@mahnunchik, @liangshan , @fernandes if you have finished your translations - please rebase them on top of master and send a PR - I'll merge (faster this time...).

Thanks!

**Comment by fernandes** [comment]
hey @jonmountjoy thank you for reply... we need to finish translation from IV. Backing Services til the end.

Once we finish I send the PR

thanks

**Comment by orangain** [comment]
@jonmountjoy Thank you for merging! Merging by hand was not an easy job, wasn't it?  I'll send an another PR to apply fix since this PR.

@fernandes Sorry for not replying sooner. It was absolutely ok, but now I'm looking forward to the day your translation is merged.

**Comment by fernandes** [comment]
@orangain we are ~50% ready... ETA is PR on next 2 weeks ;)

**Comment by mahnunchik** [comment]
Hi @jonmountjoy 

Russian translation is almost ready:
* https://github.com/mahnunchik/12factor/tree/translations
* https://ru12factor.herokuapp.com/ru/

I've asked my friends to check the translation. After that I will make PR.

**Comment by jonmountjoy** [comment]
Thanks @mahnunchik !  

I'm out for about a week - I'll take a look after I return.

**Pull request closed without merging**
