### PR TITLE
Vietnamese translation [WIP]

### PR DESCRIPTION
**Pull request by runlevel5**

### CODE REVIEW

**Comment by hienvd** [comment]
Why this pull request is still open without any comment? @raul

**Comment by joneslee85** [comment]
@hienvd not really, need some help to continue the work, been so much occupied with work lately.

**Comment by hienvd** [comment]
@joneslee85 let me review the translation and help you to continue

**Comment by joneslee85** [comment]
@hienvd thx

**Comment by thangchung** [comment]
So any updates from this PR, guys?

**Pull request closed without merging**
