### PR TITLE
Arabic Translation [WIP]

### PR DESCRIPTION
**Pull request by z0al**
Hello,

I'm working to bring Arabic-language translation. Here are what need to be done:

- [x] Add Arabic to locales
- [x] Support RTL 
- [x] Translate Introduction 
- [ ] Translate these factors:
  - [ ] Codebase
  - [ ] Dependencies
  - [ ] Config
  - [ ] Backing services
  - [ ] Build, release, run
  - [ ] Processes
  - [ ] Port binding
  - [ ] Concurrency
  - [ ] Disposability
  - [ ] Dev/prod parity
  - [ ] Logs
  - [ ] Admin processes
- [x] Reformat the locales list (typically `render_locales(factor)`) to be more readable, 3x4 table (screenshot bellow) ?

locales

### CODE REVIEW

**Comment by jonmountjoy** [comment]
👍

**Comment by AhmedRaafat14** [comment]
@z0al are you still into that do you need help?

**Comment by z0al** [comment]
Hey @AhmedRaafat14 , sorry, I'm not working on this anymore. Translation turned out to be harder than I expected. Feel free to take over if you're interested

**Comment by kingshalaby1** [comment]
hi @z0al, I need your RTL stuff. I am almost done here #285 
also your gentle review  - cc @AhmedRaafat14 - is appreciated.

**Comment by z0al** [comment]
Great work @kingshalaby1 :clap:

**Pull request closed without merging**
