### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by raul**
This PR includes a reviewed version of most of [@jaza's PR](https://github.com/heroku/12factor/pull/50). 

It's still a WIP as I haven't reviewed `dev-prod-parity`, `logs` nor `admin-processes` yet. Reviews and suggestions for these and any other pages are definitely welcome.

### CODE REVIEW

**Comment by Jaza** [comment]
@raul - thanks for your corrections so far, you're doing a very thorough job, and you're picking up many of my mistakes of "not using the best term in context" as a non-native speaker. From comparing my PR to yours, I can learn a lot!

**Comment by raul** [comment]
Thank you for the translation @Jaza ! I stopped my review after checking out [@sblancov's fork](https://github.com/sblancov/12factor): I think overall it's a much better translation. Are you planning to keep working on it anytime soon @sblancov?

**Comment by sblancov** [comment]
I'm doing... hard weeks :'( My plan is to finish a first draft and then, to review all files in order to improve some expressions. I hope complete it in about 2 weeks.
Thank you for your interest :) I feel flattered.

**Comment by raul** [comment]
Sounds good @sblancov! If you want more eyeballs on it, feel free to ping me once you complete the draft, I'll be happy to review it too. 

@Jaza - I feel really bad about not merging this PR because you did a great work (pretty awesome actually if we consider it comes for a non-native speaker!), but I sincerely think that this other fork feels more natural and will be more accessible for the reader – which I think is the criteria we should apply ultimately. Comparing the fork with this branch may be a great exercise too, so I'd encourage you to check it out if you have time.

**Pull request closed without merging**
