### PR TITLE
Greek Translation (el)

### PR DESCRIPTION
**Pull request by foo123**
This is a translation of the 12factors in greek (el)

### CODE REVIEW

**Comment by davidrouten** [comment]
:+1:

**Comment by foo123** [comment]
Do you haoppen to know when it will be available online?

**Comment by jonmountjoy** [comment]
It's live @foo123 -  see https://12factor.net/el/

Thank you for your contribution!

**Comment by gsaslis** [comment]
Looks like this fixes #214 ?

**Pull request merged**
