### PR TITLE
Brazilian Portuguese Translation

### PR DESCRIPTION
**Pull request by fernandes**
**Finished translation**

Just to keep the progress of brazilian portuguese translation.

- [x] toc.md
- [x] intro.md
- [x] background.md
- [x] who.md
- [x] I.    codebase.md
- [x] II.   dependencies.md
- [x] III.  config.md
- [x] IV.   backing-services.md
- [x] V.    build-release-run.md
- [x] VI.   processes.md
- [x] VII.  port-binding.md
- [x] VIII. concurrency.md
- [x] IX.   disposability.md
- [x] X.    dev-prod-parity.md
- [x] XI.   logs.md
- [x] XII.  admin-processes.md

I'm going to update this PR once new chapters are translated.

If you're interested in help, please send your PR at github.com/12factor/12factor-br

Thank you

### CODE REVIEW

**Comment by lfilho** [comment]
@fernandes Please update the status here when you have the chance :)

**Comment by fernandes** [comment]
thank you @lfilho just more two and we are ready to go!

**Comment by lfilho** [comment]
@fernandes we're done translating! :yellow_heart: :br: :shipit:

**Comment by fernandes** [comment]
Hi @jonmountjoy 

We've finished here. You can merge, thank you :smiley:

**Comment by jonmountjoy** [comment]
Thank you very much @fernandes @lfilho and @gwmoura!  It's live: http://12factor.net/pt_br/

**Comment by lfilho** [comment]
Awesome! Thanks

**Comment by fernandes** [comment]
:tada: really great!!!

thank you @jonmountjoy for the merge, and @gwmoura and @lfilho , was a pleasure to work with you guys!! :smile:

**Comment by gwmoura** [comment]
:smile:  :smile:  :smile:  thanks guys!!!

**Pull request merged**
