### PR TITLE
Correct jammit claims

### PR DESCRIPTION
**Pull request by raul**
Props to @stevecrozz: https://github.com/heroku/12factor/pull/9

### CODE REVIEW

**Comment by superhighfives** [comment]
LGTM! 👍

**Comment by superhighfives** [comment]
Ah, wait—looks like there's an extra closing bracket here:
```[django-assetpackager](http://code.google.com/p/django-assetpackager/))```

**Comment by superhighfives** [comment]
Fixed. LGTM! 👍

**Comment by raul** [comment]
❤️ ❤️ ❤️ ❤️ ❤️

**Pull request merged**
