### PR TITLE
Force SSL with rack-ssl-enforcer

### PR DESCRIPTION
**Pull request by maxbeizer**
cc @jonmountjoy @raul 

ready for review

### CODE REVIEW

**Comment by raul** [comment]
I run it locally and it works perfectly - which got me thinking that this change would require for the potential contributors to setup SSL locally in order to test their changes. How could we avoid that? Perhaps applying the enforcement only when `RACK_ENV` is set to `production` (and setting it in the production app if it isn't already)?

**Comment by jonmountjoy** [comment]
Good idea. 👍

**Comment by maxbeizer** [comment]
@raul how about [something like this](https://github.com/heroku/inkan/blob/master/config.ru#L9)

**Comment by raul** [comment]
Sounds good to me too @maxbeizer .

**Comment by maxbeizer** [comment]
@raul  updated

**Comment by raul** [comment]
👍 , thanks! 🚀

**Pull request merged**
