### PR TITLE
Log to `stderr` instead of `stdout`.

### PR DESCRIPTION
**Pull request by kyle-pollock**
`stdout` is for program output and `stderr` is for program logging.
The reason for this separation is so logging output does not get mixed
in with a program's intended output.

### CODE REVIEW

**Comment by karel-kahula** [comment]
since we're still stuck with splunk a bit longer on the jobs side, i suppose we'll have to make sure we're redirecting stderr to stdout in our crontabs. that should be fine right?

**Comment by kyle-pollock** [comment]
@strangemonad,

- [Go's standard library logger](https://cs.opensource.google/go/go/+/refs/tags/go1.16.6:src/log/log.go;l=76)
- C's `perror` also goes to stderr. `man 3 perror`
- Unix. Check out "The Unix Programming Environment" book.

Having a cli, or an http interface is just a low level I/O detail. A program with good architecture uses the same core, or business layer, for many interfaces. Separating `stdout` from `stderr` is still good practice.

**Review by Josh-Schmidt — APPROVED** [review]

**Review by bielusm — APPROVED** [review]

**Comment by aucampia** [comment]
More input:

[HINTS FOR WRITING UNIX TOOLS](https://monkey.org/~marius/unix-tools-hints.html)

> Place diagnostics output on stderr. Diagnostics output includes anything that is not the primary data output of your tool. Among these are: progress indicators, debugging output, log messages, error messages, and usage information. When diagnostics output is intermingled with data, it is very difficult to parse, and thus compose, the tool’s output. What’s more, stderr makes diagnostics output more useful since, even if stdout is being filtered or redirected, stderr keeps printing to the user’s terminal—the ultimate target of diagnostics output.

**Comment by NathanConroy** [comment]
Hello, I'm curious about the status of this change. Will this be the 12-factor-app's new recommendation? If so, when? If not, why not? Thank you for your answer in advance!

**Comment by alkuzad** [comment]
IMHO this is not valid PR for 12factory
"The twelve-factor app is a methodology for building software-as-a-service apps that..."

Proposed change focuses on CLI apps or UNIX tools that serve different purpose and are handled differently. Cloud implementations stdout and stderr are redirected to one common logs processor anyway and keeping everything to stdout simplifies logging.  Change makes sense in local context when you run `my-app 2>/dev/null | grep XYZ` but not in the software-as-a-service one where logs are often pushed into centralized logging system with level and context to rely on instead of stream.

**Comment by chris24sahadeo** [comment]
@alkuzad You make a valid point, but I think it best for https://12factor.net/logs to still point the general dev community in the best direction, even if it does not directly relate to the "methodology for building software-as-a-service apps." 

In my experience (as I suspect a lot of others on this thread), it is best practice when developing locally to reserve `stdout` for app output and `stderr` for all other logging info (as @aucampia [pointed out](https://github.com/heroku/12factor/pull/295#issuecomment-1007336955)). Sure it may not matter when the app is deployed in the cloud, but it would be great if starting devs understood the benefit of using `stdout` and `stderr` in the conventional way, so that they can also do so if they develop non-SaaS for non-cloud environments.

I'd also be supportive of adding on a short paragraph highlighting these intricacies being discussed on this thread.

**Comment by alkuzad** [comment]
@chris24sahadeo 

I do agree that the 12factor approach should focus on the general developer experience. Web development is quite different from traditional POSIX. Web applications do not log user-visible output to the console; only debugging data is sent via HTTP requests served by the server.

We have outgrown this split by using modern libraries that split by multiple factors, such as log levels and filters. If we allow for two logging streams with vastly different formats of output, it makes it difficult for logging to be processed and sent, and can even break logging entirely. POSIX's definition of logs ended where the STDERR stream did. In the modern world, there are multiple hops between web applications and developers:

1. Docker container/K8s pod
2. Log collector/sidecar
3. Log processor and metadata extender
4. Logs storage engine
5. Logs search engine

It's helpful if we keep the log format the same and output in one place. Otherwise, decisions have to be made:

Is STDERR automatically an error stream or just an "everything stream" that contains errors, debugging, garbage collectors debug output, Nginx logs, etc.?
Is STDERR worthy of parsing at all if it can include debugging data that is not application-related (like JAVA GC logs)?
Should we send the stream name to the logging system or just merge these two together? (like K8s does)
What do we do if logs don't match the structured logging format in STDERR? Convert them to JSON to make them safe to process? Discard them fully?
If STDERR is a debug output, what is STDOUT then? If POSIX rules apply, no data should be there in the correct web application design. Should STDOUT be discarded fully then? What if someone does not know about this discard convention?
Without these new challenges, I would agree that the split is valid. With them in place, I do think the current proposal is easier to understand for everyone.

As for @aucampia's comment, the application is running outside the 12factor context, so these rules do not apply. It does not mean, however, that we should transfer POSIX rules back, due to the reasons mentioned.

**Comment by chris24sahadeo** [comment]
Thanks @alkuzad for taking the time to explain this. Admittedly I am no expert on web development, so I'll take your points as a roadmap for learning more.

**Pull request closed without merging**
