### PR TITLE
Update background.md

### PR DESCRIPTION
**Pull request by greenplace**
Исправлены ошибки в орфографии и пунктуации.

### CODE REVIEW

**Comment by jonmountjoy** [comment]
Thanks

**Comment by jonmountjoy** [comment]
Sorry @greenplace I can no longer merge this automatically.  Can you please edit so that I can, if it's still necessary?

**Comment by mahnunchik** [comment]
Hi @greenplace 
Could you please edit your changes?

**Comment by raul** [comment]
Thank you - rebased in https://github.com/heroku/12factor/pull/169

**Pull request closed without merging**
